apiVersion: v1
kind: Deployment
metadata:
  name: yolo-backend-deployment
  labels:
    app: api
    layer: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      layer: backend
  template:
    metadata:
      labels:
        app: api
        layer: backend
    spec:
      containers:
        - name: yolo-backend
          image: cheronok/yolo-backend:1.0
          command: ["npm", "start"]
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb:27017/yolomy"
          ports:
            - containerPort: 5000
              protocol: TCP