apiVersion: v1
kind: Deployment
metadata:
  name: yolo-client-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: yolo-client
          image: cheronok/yolo-client:1.0
          command: ["npm", "start"]
          ports:
            - containerPort: 3000
              protocol: TCP